language: node_js
node_js: 
 - "6"
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
 - sleep 15
 - npm install -g supervisor